GET http://localhost:3000/

###

GET http://localhost:3000/user/Elisa/Bariselli/eb@studenti.polito.it/12-05-2002

###

GET http://localhost:3000/user/Elisa

###

GET http://localhost:3000/user/id/1

###
GET http://localhost:3000/api/options