GET http://localhost:3000/
###

GET http://localhost:3000/user
###

POST http://localhost:3000/user
Content-Type: application/json

{ "name": "Jim", "id": 99 }
###

GET http://localhost:3000/user/30/name
###

GET http://localhost:3000/show/proteins
###

GET http://localhost:3000/show/food/17
###